language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: ISBAry4CHwd6/zXnhmvkruihmdAt7JpPsCegMrxvmy71ytIeQYVNXSlGlEhgSSRneslxC20G4mFI1GPQVqFvZ+IvWzwiQJ7p/+fVyBgSoPDifdXkTEudGXfuJ6Xwd4aK5XxkgAdKbPof7Kc6uvA4eE4Di60AZSDVr9mqQfYPOiZNkG4PTpTUV0BGbB9WGFWlObULrKUzZa2+Mcvs1XuJhM3q7wvQ4OOFrvUrDJldiIB/JiBr9hgC8JyIRbudtcZwTGzHSg2iegafUJkTHMb7l3zHW+kxaV5bLsA+KJk7/52H1RDTHKY6Qsa2muznSyHcjonZurOvh7G7zn/3XgTtBBGGsey6RD0oTI0ROcToabKQF8gbv6gjF5f2qlKz9hrAGfV8bU1bk+RaE2VMW1UUPsMldeXUwofmjaPSBM6POmBnSlpVZ8CAuE/U0p5HqpZ+83BPLpXReAqd2gniCgCGbc+fSP795R9bPzsOEnICRNVKz0dYefeC1zVgon0a+r5xmXhZXrqR6VgJwJDHSEyWa1oPpZfeOv4VzMJDlj3bBWKZ1AjBHqOQeVyS7a7DIclxi9GRx9H9O3We3taYcSZ5aeTKQKHqDav7o/T2DBjfA2MpuRIDHq6sWIxgUlWMI3Ivedt4L7q/VT4XHVBmDHsP5n/Iny2NLUWQTlpO309hj+0=
  app: infinite-tor-16145
  on:
    repo: Vlodnik/Blog-Api
